spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/juanMoyano100/microserviciosSleep
          username: JuanMoyano100
          password: GitHub11061996

# Reference: https://cloud.spring.io/spring-cloud-static/spring-cloud-config/2.1.4.RELEASE/single/spring-cloud-config.html#_authentication
